replicaCount: 1

image:
  repository: jasmine150720/vdt2024-react
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 100Mi

service:
  type: NodePort
  port: 3000
  nodePort: 30100
  
